Traceback (most recent call last):
  File "main.py", line 12, in main
  File "db_connection.py", line 33, in __init__
  File "PIL\Image.py", line 3431, in open
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Sistema\\Painel_Pedidos\\dist\\img\\logo.png'
